# Generated by Django 5.1.6 on 2025-02-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('buy', models.CharField(max_length=20)),
                ('sell', models.CharField(max_length=20)),
                ('nbt', models.CharField(max_length=20)),
            ],
        ),
    ]
