# Generated by Django 5.1.6 on 2025-02-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='buy',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='nbt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sell',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
