services:
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  # Фронтенд - DEV режим (один Vue.js проект)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Исключаем node_modules из volume
    ports:
      - "8080:8080"  # Один порт для Vite dev server
    depends_on:
      - web

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/usr/share/nginx/html/static:ro
    depends_on:
      - frontend
      - web

  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:7
    restart: always

  celery:
    build: .
    command: sh -c "sleep 10 && celery -A myproject worker --loglevel=info"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build: .
    command: sh -c "sleep 15 && celery -A myproject beat --loglevel=info"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume: